#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/bin/tr69d

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param env \
		TR69_TRANSFORMER_SCRIPT=/usr/lib/tr69d/transformer.lua \
		TR69_DEVICE_MAP=/etc/transformer/maps/Device.map
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger tr69
}

reload_service() {
	ubus call tr69 reload '{}' >/dev/null
}
